From itsafeaturemythic/python38_sanic_c2profile:0.0.3
RUN pip uninstall -y mythic_c2_container
RUN pip install mythic_c2_container==0.0.15
RUN apt-get update && apt-get install apt-file -y && apt-file update && apt-get install vim -y